apiVersion: 1

datasources:
        - name: InfluxDB
          type: influxdb
          access: proxy
          orgID: 1
          url: http://influxdb-svc:8086
          database: grafana
          user: graf_adm
          password: graf_adm_pass
          isDefault: true
          version: 1
          editable: true
