apiVersion: v1
kind: Service
metadata:
        name: ftps-svc
        annotations:
                metallb.universe.tf/allow-shared-ip: ftservices
        labels:
                app: ftps
spec:
        type: LoadBalancer
        loadBalancerIP: 172.17.0.230
        selector:
                app: ftps
        ports:
        - port: 21
          targetPort: 21
          name: ftps
        - port: 40000
          targetPort: 40000
          name: ftps00

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: ftps
        labels:
                app: ftps
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: ftps
        template:
                metadata:
                        labels:
                                app: ftps
                spec:
                        containers:
                        - name: ftps
                          image: service_ftps
                          imagePullPolicy: Never
                          ports:
                          - containerPort: 21
                          - containerPort: 40000
