apiVersion: v1
kind: Service
metadata:
        name: influxdb-svc
        labels:
                app: influxdb
spec:
        type: ClusterIP
        selector:
                app: influxdb
        ports:
        - port: 8086
          targetPort: 8086
          name: influxdb

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: influxdb-pvc
spec:
        storageClassName: ""
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: influxdb
        labels:
                app: influxdb
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: influxdb
        template:
                metadata:
                        labels:
                                app: influxdb
                spec:
                        containers:
                        - name: influxdb
                          image: service_influxdb
                          imagePullPolicy: Never
                          livenessProbe:
                                  exec:
                                          command:
                                          - /root/./livenessprobe.sh
                                  initialDelaySeconds: 50
                                  periodSeconds: 10
                                  failureThreshold: 2
                          ports:
                          - containerPort: 8086
                          volumeMounts:
                          - name: influxdb-pvc
                            mountPath: /var/lib/influxdb
                        volumes:
                        - name: influxdb-pvc
                          persistentVolumeClaim:
                                  claimName: influxdb-pvc
