apiVersion: v1
kind: Service
metadata:
        name: nginx-svc
        annotations:
                metallb.universe.tf/allow-shared-ip: ftservices
        labels:
                app: nginx
spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.240
        selector:
                app: nginx
        ports:
        - port: 22
          targetPort: 22
          name: ssh
        - port: 80
          targetPort: 80
          name: http
        - port: 443
          targetPort: 443
          name: https

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx
        labels:
                app: nginx
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: nginx
        template:
                metadata:
                        labels:
                                app: nginx
                spec:
                        containers:
                        - name: nginx
                          image: service_nginx
                          imagePullPolicy: Never
                          ports:
                          - containerPort: 22
                          - containerPort: 80
                          - containerPort: 443
