apiVersion: v1
kind: Service
metadata:
        name: phpmyadmin-svc
        annotations:
                metallb.universe.tf/allow-shared-ip: ftservices
        labels:
                app: phpmyadmin
spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.240
        selector:
                app: phpmyadmin
        ports:
        - port: 5000
          targetPort: 5000
          name: phpmyadmin-http

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: phpmyadmin
        labels:
                app: phpmyadmin
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: phpmyadmin
        template:
                metadata:
                        labels:
                                app: phpmyadmin
                spec:
                        containers:
                        - name: phpmyadmin
                          image: service_phpmyadmin
                          imagePullPolicy: Never
                          ports:
                          - containerPort: 5000
