kind: PersistentVolume
apiVersion: v1
metadata:
        name: pv0001
spec:
        storageClassName: ""
        capacity:
                storage: 1Gi
        accessModes:
                - ReadWriteOnce
        hostPath:
                path: /pv0001
                type: DirectoryOrCreate
