apiVersion: v1
kind: Service
metadata:
        name: wordpress-svc
        annotations:
                metallb.universe.tf/allow-shared-ip: ftservices
        labels:
                app: wordpress
spec:
        type: LoadBalancer
        loadBalancerIP: 172.17.0.230
        selector:
                app: wordpress
        ports:
        - port: 5050
          targetPort: 5050
          name: wp-http

---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: wordpress
        labels:
                app: wordpress
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: wordpress
        template:
                metadata:
                        labels:
                                app: wordpress
                spec:
                        containers:
                        - name: wordpress
                          image: service_wordpress
                          imagePullPolicy: Never
                          livenessProbe:
                                  exec:
                                          command:
                                          - /root/./livenessprobe.sh
                                  initialDelaySeconds: 20
                                  periodSeconds: 10
                                  failureThreshold: 2
                          ports:
                          - containerPort: 5050
